In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option("display.max_columns",None)

In [4]:
network_data=pd.read_csv('B:/spyder/OBS_Network_data.csv',header=None,delimiter=" *, *",engine='python')
print(network_data.head())

   0         1         2     3         4          5          6         7   \
0   3  0.822038  0.190381  1000  0.004815  19.031487  19.038129  0.809619   
1   3  0.923707  0.090383   900  0.000633   9.035834   9.038339  0.909617   
2   3  0.905217  0.108670   800  0.000497  10.864208  10.866977  0.891330   
3   3  0.912327  0.102633   700  0.000423  10.252196  10.263258  0.897367   
4   3  0.859478  0.153514   500  0.000443  15.344782  15.351421  0.846486   

           8           9     10     11     12     13         14         15  \
0  822.037500  177.962500  1440  90324  73128  17196  130066560  105304320   
1  831.336000   68.664000  1440  81276  73930   7346  117037440  106459200   
2  724.173750   75.826250  1440  72228  64379   7849  104008320   92705760   
3  638.628775   61.371225  1440  63284  56789   6495   91128960   81776160   
4  429.738750   70.261250  1440  45188  38251   6937   65070720   55081440   

         16        17        18 19        20             21  
0  0.1

In [5]:
print(network_data.shape)


(1075, 22)


In [6]:
network_data.columns=["Node","Utilised Bandwith Rate","Packet Drop Rate","Full_Bandwidth","Average_Delay_Time_Per_Sec",
"Percentage_Of_Lost_Pcaket_Rate","Percentage_Of_Lost_Byte_Rate","Packet Received Rate","of Used_Bandwidth",
"Lost_Bandwidth","Packet Size_Byte","Packet_Transmitted","Packet_Received","Packet_lost","Transmitted_Byte",
"Received_Byte","10-Run-AVG-Drop-Rate","10-Run-AVG-Bandwith-Use","10-Run-Delay","Node Status","Flood Status","Class"]

In [7]:
print(network_data.head())


   Node  Utilised Bandwith Rate  Packet Drop Rate  Full_Bandwidth  \
0     3                0.822038          0.190381            1000   
1     3                0.923707          0.090383             900   
2     3                0.905217          0.108670             800   
3     3                0.912327          0.102633             700   
4     3                0.859478          0.153514             500   

   Average_Delay_Time_Per_Sec  Percentage_Of_Lost_Pcaket_Rate  \
0                    0.004815                       19.031487   
1                    0.000633                        9.035834   
2                    0.000497                       10.864208   
3                    0.000423                       10.252196   
4                    0.000443                       15.344782   

   Percentage_Of_Lost_Byte_Rate  Packet Received Rate  of Used_Bandwidth  \
0                     19.038129              0.809619         822.037500   
1                      9.038339           

In [8]:
network_data.isnull().sum()


Node                              0
Utilised Bandwith Rate            0
Packet Drop Rate                  0
Full_Bandwidth                    0
Average_Delay_Time_Per_Sec        0
Percentage_Of_Lost_Pcaket_Rate    0
Percentage_Of_Lost_Byte_Rate      0
Packet Received Rate              0
of Used_Bandwidth                 0
Lost_Bandwidth                    0
Packet Size_Byte                  0
Packet_Transmitted                0
Packet_Received                   0
Packet_lost                       0
Transmitted_Byte                  0
Received_Byte                     0
10-Run-AVG-Drop-Rate              0
10-Run-AVG-Bandwith-Use           0
10-Run-Delay                      0
Node Status                       0
Flood Status                      0
Class                             0
dtype: int64

In [9]:
##creat a copy of the data frame
network_data_rev=pd.DataFrame.copy(network_data)
network_data_rev.head()

Node  Utilised Bandwith Rate  Packet Drop Rate  Full_Bandwidth  \
0     3                0.822038          0.190381            1000   
1     3                0.923707          0.090383             900   
2     3                0.905217          0.108670             800   
3     3                0.912327          0.102633             700   
4     3                0.859478          0.153514             500   

   Average_Delay_Time_Per_Sec  Percentage_Of_Lost_Pcaket_Rate  \
0                    0.004815                       19.031487   
1                    0.000633                        9.035834   
2                    0.000497                       10.864208   
3                    0.000423                       10.252196   
4                    0.000443                       15.344782   

   Percentage_Of_Lost_Byte_Rate  Packet Received Rate  of Used_Bandwidth  \
0                     19.038129              0.809619         822.037500   
1                      9.038339              0.909617         831.336000   
2                     10.866977              0.891330         724.173750   
3                     10.263258              0.897367         638.628775   
4                     15.351421              0.846486         429.738750   

   Lost_Bandwidth  Packet Size_Byte  Packet_Transmitted  Packet_Received  \
0      177.962500              1440               90324            73128   
1       68.664000              1440               81276            73930   
2       75.826250              1440               72228            64379   
3       61.371225              1440               63284            56789   
4       70.261250              1440               45188            38251   

   Packet_lost  Transmitted_Byte  Received_Byte  10-Run-AVG-Drop-Rate  \
0        17196         130066560      105304320              0.146594   
1         7346         117037440      106459200              0.058749   
2         7849         104008320       92705760              0.076069   
3         6495          91128960       81776160              0.081080   
4         6937          65070720       55081440              0.108995   

   10-Run-AVG-Bandwith-Use  10-Run-Delay Node Status  Flood Status  \
0                 0.780936      0.001838           B      0.023455   
1                 0.886758      0.001751           B      0.000000   
2                 0.869009      0.001767           B      0.000000   
3                 0.866710      0.001959           B      0.000000   
4                 0.850883      0.002242           B      0.000000   

           Class  
0  'NB-No Block'  
1     'No Block'  
2     'No Block'  
3     'No Block'  
4     'No Block'

In [10]:
network_data_rev=network_data_rev.drop('Packet Size_Byte',axis=1)


In [11]:
network_data_rev.shape


(1075, 21)

In [15]:
colname=['Node','Full_Bandwidth','Node Status','Class']


In [16]:
from sklearn import preprocessing

colname=['Node','Full_Bandwidth','Node Status','Class']
le={}

for x in colname:
    le[x]=preprocessing.LabelEncoder()
for x in colname:
    network_data_rev[x]=le[x].fit_transform(network_data_rev.__getattr__(x))

In [17]:
network_data_rev.head()


Node  Utilised Bandwith Rate  Packet Drop Rate  Full_Bandwidth  \
0     0                0.822038          0.190381               9   
1     0                0.923707          0.090383               8   
2     0                0.905217          0.108670               7   
3     0                0.912327          0.102633               6   
4     0                0.859478          0.153514               4   

   Average_Delay_Time_Per_Sec  Percentage_Of_Lost_Pcaket_Rate  \
0                    0.004815                       19.031487   
1                    0.000633                        9.035834   
2                    0.000497                       10.864208   
3                    0.000423                       10.252196   
4                    0.000443                       15.344782   

   Percentage_Of_Lost_Byte_Rate  Packet Received Rate  of Used_Bandwidth  \
0                     19.038129              0.809619         822.037500   
1                      9.038339              0.909617         831.336000   
2                     10.866977              0.891330         724.173750   
3                     10.263258              0.897367         638.628775   
4                     15.351421              0.846486         429.738750   

   Lost_Bandwidth  Packet_Transmitted  Packet_Received  Packet_lost  \
0      177.962500               90324            73128        17196   
1       68.664000               81276            73930         7346   
2       75.826250               72228            64379         7849   
3       61.371225               63284            56789         6495   
4       70.261250               45188            38251         6937   

   Transmitted_Byte  Received_Byte  10-Run-AVG-Drop-Rate  \
0         130066560      105304320              0.146594   
1         117037440      106459200              0.058749   
2         104008320       92705760              0.076069   
3          91128960       81776160              0.081080   
4          65070720       55081440              0.108995   

   10-Run-AVG-Bandwith-Use  10-Run-Delay  Node Status  Flood Status  Class  
0                 0.780936      0.001838            1      0.023455      0  
1                 0.886758      0.001751            1      0.000000      1  
2                 0.869009      0.001767            1      0.000000      1  
3                 0.866710      0.001959            1      0.000000      1  
4                 0.850883      0.002242            1      0.000000      1

In [21]:
#creating training and testing
X=network_data_rev.values[:,:-1]
Y=network_data_rev.values[:,-1]

In [22]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)
X=scaler.transform(X)

Y=Y.astype(int)

In [23]:
from sklearn.model_selection import train_test_split

x_train , x_test  , y_train , y_test = train_test_split(X , Y , 
                                                        test_size = 0.3 ,
                                                        random_state = 10)

In [24]:
#Running the decision tree model
#predicting using decision_Tree_Classifier
#from sklearn import svm
#model_DecisionTree=svm.SVC(kernel='rbf',C=1.0,gamma=0.1)

from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier()
model_DecisionTree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [28]:
#fit the model on data and predict the values.
y_pred=model_DecisionTree.predict(x_test)

print(list(zip(y_test,y_pred)))

[(2, 2), (3, 3), (3, 3), (1, 1), (2, 2), (0, 0), (3, 3), (2, 2), (0, 0), (0, 0), (0, 0), (1, 1), (2, 2), (0, 0), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (3, 3), (3, 3), (3, 3), (3, 3), (1, 1), (0, 0), (0, 0), (2, 2), (1, 1), (0, 0), (3, 3), (3, 3), (1, 1), (3, 3), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (2, 2), (3, 3), (0, 0), (3, 3), (0, 0), (2, 2), (3, 3), (0, 0), (0, 0), (3, 3), (3, 3), (2, 2), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (1, 1), (3, 3), (3, 3), (3, 3), (0, 0), (3, 3), (3, 3), (0, 0), (1, 1), (1, 1), (0, 0), (2, 2), (0, 0), (0, 0), (3, 3), (3, 3), (0, 0), (0, 0), (0, 0), (0, 0), (3, 3), (0, 0), (1, 1), (2, 2), (3, 3), (0, 0), (3, 3), (3, 3), (0, 0), (0, 0), (0, 0), (1, 1), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (3, 3), (0, 0), (3, 3), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (3, 3), (0, 0), (3, 3), (3, 3), (0, 0), (3, 3), (3, 3), (0, 0), (0, 0), (0, 0), (3, 3), (0, 0), (0, 0),

In [29]:
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[146   0   0   0]
 [  0  45   0   0]
 [  0   0  40   0]
 [  0   0   0  92]]
1.0
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       146
          1       1.00      1.00      1.00        45
          2       1.00      1.00      1.00        40
          3       1.00      1.00      1.00        92

avg / total       1.00      1.00      1.00       323



In [30]:
from sklearn import cross_validation

kfold_cv=cross_validation.KFold(n=len(x_train),n_folds=10)
print(kfold_cv)

#running the model using scoring as accuracy
kfold_cv_result=cross_validation.cross_val_score(estimator=model_DecisionTree,X=x_train,y=y_train,
                                                 scoring="accuracy",cv=kfold_cv)
print(kfold_cv_result)
#finding the mean
print(kfold_cv_result.mean())

sklearn.cross_validation.KFold(n=752, n_folds=10, shuffle=False, random_state=None)
[ 1.          1.          0.98666667  1.          1.          1.          1.
  1.          1.          1.        ]
0.998666666667


C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [31]:
###For generating the tree 
###Click on the link http://www.webgraphviz.com/
from sklearn import tree
with open("model_DecisionTree.txt","w") as f:
    f=tree.export_graphviz(model_DecisionTree,out_file=f)

In [32]:
#Running extra tree classifier
#predicting using bagging classifier
    
from sklearn.ensemble import ExtraTreesClassifier

model=(ExtraTreesClassifier(21))
#fit the model on the data and predict the value

model=model.fit(x_train,y_train)

y_pred=model.predict(x_test)

In [33]:
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[146   0   0   0]
 [  0  45   0   0]
 [  0   0  40   0]
 [  0   0   0  92]]
1.0
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       146
          1       1.00      1.00      1.00        45
          2       1.00      1.00      1.00        40
          3       1.00      1.00      1.00        92

avg / total       1.00      1.00      1.00       323



In [34]:
##Running RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
model_RandomForest=RandomForestClassifier(501)

model_RandomForest=model.fit(x_train,y_train)

y_pred=model_RandomForest.predict(x_test)

In [35]:
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[146   0   0   0]
 [  0  45   0   0]
 [  0   0  40   0]
 [  0   0   0  92]]
1.0
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       146
          1       1.00      1.00      1.00        45
          2       1.00      1.00      1.00        40
          3       1.00      1.00      1.00        92

avg / total       1.00      1.00      1.00       323



In [36]:
#running AdaBoostClassifier 

from sklearn.ensemble import AdaBoostClassifier

model_AdaBoost=(AdaBoostClassifier(base_estimator=DecisionTreeClassifier(),n_estimators=100))

model_AdaBoost.fit(x_train,y_train)

y_pred=model_AdaBoost.predict(x_test)

In [37]:
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[146   0   0   0]
 [  0  45   0   0]
 [  0   0  40   0]
 [  0   0   0  92]]
1.0
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       146
          1       1.00      1.00      1.00        45
          2       1.00      1.00      1.00        40
          3       1.00      1.00      1.00        92

avg / total       1.00      1.00      1.00       323



In [38]:
#running Gradient Boosting classfier

from sklearn.ensemble import GradientBoostingClassifier

model_GradientBoosting=GradientBoostingClassifier()

model_GradientBoosting.fit(x_train,y_train)

y_pred=model_GradientBoosting.predict(x_test)

In [39]:
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[146   0   0   0]
 [  0  45   0   0]
 [  0   0  40   0]
 [  0   0   0  92]]
1.0
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       146
          1       1.00      1.00      1.00        45
          2       1.00      1.00      1.00        40
          3       1.00      1.00      1.00        92

avg / total       1.00      1.00      1.00       323



In [40]:
#voting classfier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [41]:
#creating submodel

estimators=[]
model1=LogisticRegression()
estimators.append(('log',model1))
model2=DecisionTreeClassifier()
estimators.append(('cart',model2))
model3=SVC()
estimators.append(('svm',model3))

In [42]:
#creating the ensembel model
ensemble=VotingClassifier(estimators)
ensemble.fit(x_train,y_train)

y_pred=ensemble.predict(x_test)

In [43]:
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[139   3   0   4]
 [  0  45   0   0]
 [  0   0  40   0]
 [ 25   0   0  67]]
0.90092879257
             precision    recall  f1-score   support

          0       0.85      0.95      0.90       146
          1       0.94      1.00      0.97        45
          2       1.00      1.00      1.00        40
          3       0.94      0.73      0.82        92

avg / total       0.91      0.90      0.90       323

